<?php

require_once __DIR__ . "/fpdf/fpdf.php";

class ReportPDF extends FPDF
{
    public $reportTitle = "";

    private $rowFill = false;

public $generatedBy = "";

public $dateFrom = "";

public $dateTo = "";

    function Header()
    {
        // Logo (optional)
        // $this->Image(__DIR__.'/../../assets/logo.png',10,8,18);

        // Company
        $this->SetFont('Arial','B',18);
        $this->SetTextColor(26,111,196);
        $this->Cell(0,10,'PHARMAADMIN',0,1,'C');

        $this->SetFont('Arial','',10);
        $this->SetTextColor(100,100,100);
        $this->Cell(0,6,'Pharmacy Management & Online Marketplace',0,1,'C');

        $this->Ln(3);

        $this->SetDrawColor(220,220,220);
        $this->Line(10,30,200,30);

        $this->Ln(5);

        $this->SetTextColor(0,0,0);
        $this->SetFont('Arial','B',14);

        $this->Cell(0,8,$this->reportTitle,0,1,'C');

        $this->Ln(5);
    }

    function Footer()
    {
        $this->SetY(-18);

        $this->SetDrawColor(220,220,220);
        $this->Line(10,$this->GetY(),200,$this->GetY());

        $this->Ln(3);

        $this->SetFont('Arial','I',8);

        $this->Cell(
            0,
            5,
            'Generated by PharmaAdmin | Page '.$this->PageNo().'/{nb}',
            0,
            0,
            'C'
        );
    }

public function createReport($config)
{
    $this->reportTitle = $config["title"] ?? "";

    $this->generatedBy = $config["generatedBy"] ?? "";

    $this->dateFrom = $config["from"] ?? "";

    $this->dateTo = $config["to"] ?? "";

    $this->AliasNbPages();

    $this->AddPage();

    $this->reportInfo(
        $this->dateFrom,
        $this->dateTo,
        $this->generatedBy
    );
}
    function reportInfo($from,$to,$user)
    {
        $this->SetFont('Arial','',10);

        $this->Cell(45,7,'Generated By:',0,0);
        $this->Cell(70,7,$user,0,0);

        $this->Cell(30,7,'Generated:',0,0);
        $this->Cell(0,7,date('d M Y H:i'),0,1);

        $this->Cell(45,7,'Date Range:',0,0);
        $this->Cell(0,7,$from."  to  ".$to,0,1);

        $this->Ln(4);
    }

    public function sectionTitle($title)
{
    $this->SetFillColor(26,111,196);
    $this->SetTextColor(255,255,255);
    $this->SetFont('Arial','B',11);

    $this->Cell(190,8,$title,0,1,'L',true);

    $this->Ln(2);

    $this->SetTextColor(0,0,0);
}
public function tableHeader($headers,$widths)
{
    $this->SetFont('Arial','B',9);

    $this->SetFillColor(240,245,250);

    foreach($headers as $i=>$header){

        $this->Cell(
            $widths[$i],
            8,
            $header,
            1,
            0,
            'C',
            true
        );

    }

    $this->Ln();
}
public function tableRow($data,$widths)
{
    $this->checkPageBreak();

    if($this->rowFill){
        $this->SetFillColor(248,249,250);
    }else{
        $this->SetFillColor(255,255,255);
    }

    $this->SetFont('Arial','',8);

    foreach($data as $i=>$value){

        $align = "L";

        if(is_numeric(str_replace(["GHS"," ",","],"",$value))){
            $align = "R";
        }

        $this->Cell(
            $widths[$i],
            8,
            $value,
            1,
            0,
            $align,
            true
        );

    }

    $this->Ln();

    $this->rowFill = !$this->rowFill;
}
public function summaryItem($label,$value)
{
    $this->SetFont('Arial','B',10);

    $this->Cell(55,8,$label,1);

    $this->SetFont('Arial','',10);

    $this->Cell(45,8,$value,1);

    $this->Ln();
}
public function download($filename)
{
    $this->Output("D",$filename);
}

public function addTable($headers,$rows,$widths)
{
    $this->sectionTitle("Report Details");

    $this->tableHeader($headers,$widths);

    foreach($rows as $row){

        $this->tableRow($row,$widths);

    }
}
public function addStatistics($stats)
{
    $this->sectionTitle("Report Summary");

    foreach($stats as $label=>$value){

        if(is_numeric($value)){

            if(stripos($label,"revenue") !== false){

                $value = $this->money($value);

            }

        }

        $this->summaryItem($label,$value);

    }

    $this->Ln(4);
}
public function checkPageBreak($height = 8)
{
    if($this->GetY() + $height > 270){
        $this->AddPage();
    }
}

public function money($amount)
{
    return "GHS " . number_format((float)$amount,2);
}

}